=== pmcastell/prj.old/prj/php/tema3-4-xml/BDhospital.dtd
<!ELEMENT BDhospital (Hospital*,Sala*,Plantilla*,Ocupacion*,Doctor*,enfermo*)+>
<!ELEMENT Hospital EMPTY>
    <!ATTLIST Hospital hospital_cod NMTOKEN #REQUIRED 
                       nombre NMTOKENS #REQUIRED
                       direccion CDATA #REQUIRED 
                       telefono NMTOKEN #REQUIRED
                       num_camas NMTOKEN #REQUIRED>
<!ELEMENT Sala EMPTY>
    <!ATTLIST Sala hospital_cod NMTOKEN #REQUIRED 
                   sala_cod NMTOKEN #REQUIRED
                   nombre NMTOKENS #REQUIRED 
                   num_cama NMTOKEN #REQUIRED>
                   
<!ELEMENT Plantilla EMPTY>
    <!ATTLIST Plantilla hospital_cod NMTOKEN #REQUIRED 
                        sala_cod NMTOKEN #REQUIRED
                        empleado_num NMTOKEN #REQUIRED 
                        apellido NMTOKENS #REQUIRED
                        funcion NMTOKENS #REQUIRED 
                        turno (Mañana|Tarde|Noche) #REQUIRED
                        salario NMTOKEN #REQUIRED>
<!ELEMENT Ocupacion EMPTY>
    <!ATTLIST Ocupacion inscripcion NMTOKEN #REQUIRED 
                        hospital_cod NMTOKEN #REQUIRED
                        sala_cod NMTOKEN #REQUIRED 
                        cama NMTOKEN #REQUIRED>
<!ELEMENT Doctor EMPTY>
    <!ATTLIST Doctor hospital_cod NMTOKEN #REQUIRED 
                     doctor_num NMTOKEN #REQUIRED
                     apellido NMTOKENS #REQUIRED 
                     especialidad (Psiquiatra|Psicologo|Cirujano|Pediatra) #REQUIRED>
<!ELEMENT enfermo EMPTY>
    <!ATTLIST enfermo inscripcion NMTOKEN #REQUIRED 
                      apellido NMTOKENS #REQUIRED
                      direccion CDATA #REQUIRED 
                      fecha_nac_dia (01|02|03|04|31) #REQUIRED
                      fecha_nac_mes (01|02|03|04|05|06|07|08|09|10|11|12) #REQUIRED
                      fecha_nac_año CDATA #REQUIRED 
                      s (H |h|M|m) #REQUIRED
                      ss NMTOKENS #REQUIRED>

=== pmcastell/prj.old/prj/php/tema3-4-xml/BDhospital.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
     Hospital (hospital_cod, nombre, direccion, telefono, num_camas); 
     Sala(hospital_cod, sala_cod, nombre, num_cama); 
     Plantilla (hospital_cod, sala_cod,empleado_num, apellido, funcion, turno, salario ); 
     Ocupacion (inscripcion,hospital_cod, sala_cod, cama); 
     Doctor (hospital_cod, doctor_num, apellido,especialidad); 
     enfermo (inscripcion,apellido,direccion,fecha_nac,s,nss); 
-->
<!-- 
<!DOCTYPE BDhospital SYSTEM "BDhospital.dtd">
<BDhospital>
 -->

<BDhospital  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xsi:noNamespaceSchemaLocation="BDhospital.xsd">

	<Hospital hospital_cod="1" nombre="La Paz" direccion="C/ a,3"
		telefono="954332211" num_camas="3" />
	<Hospital hospital_cod="2" nombre="La Paz" direccion="C/ a,3"
        telefono="954332211" num_camas="3" /> 
	<Sala hospital_cod="1" sala_cod="1" nombre="Quirófano" num_cama="2"/>
	<Plantilla hospital_cod="1" sala_cod="1" empleado_num="1" apellido="LÓPEZ" funcion="Administrativo" 
	   turno="Mañana" salario="3000"/>
	<Ocupacion inscripcion="122" hospital_cod="1" sala_cod="1" cama="3"/>   
	<Ocupacion inscripcion="123" hospital_cod="2" sala_cod="1" cama="15"/>
	<Doctor hospital_cod="7" doctor_num="087" apellido="PÉREZ" especialidad="Psiquiatra" />
	<enfermo inscripcion="122" apellido="PÉREZ" direccion="akaka, 12" fecha_nac_dia="01" 
	           fecha_nac_mes="11" fecha_nac_año="2222"
	           s="M" ss="123456789012"/>
</BDhospital>
