=== pmcastell/prj.old/php/tema3-4-xml/estructuraBd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	version="0.1" xml:lang="es">
	<xs:element name="estructuraBD">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="tabla" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="campo" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="nombre" type="tipoIdVal" />
									<xs:attribute name="tipo" type="tiposValidos" />
									<xs:attribute name="longitud" type="xs:integer"
										use="optional" />
									<xs:attribute name="lista_de_valores" type="tipoListaValores"
										use="optional" />
									<xs:attribute name="null" type="xs:boolean" use="optional"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="primary_key">
								<xs:complexType>
									<xs:attribute name="campos_clave" type="tipoListaIdVal" />
								</xs:complexType>
							</xs:element>
							<xs:element name="foreign_key" minOccurs="0"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="campos_clave" type="tipoListaIdVal" />
									<xs:attribute name="tabla_ajena" type="tipoIdVal" />
									<xs:attribute name="campos_relacionados" type="tipoListaIdVal" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="nombre" type="tipoIdVal" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="nombre" type="tipoIdVal" />
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="tipoIdVal">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-z][a-zA-Z0-9_]*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoListaIdVal">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="replace" />
			<xs:pattern value="([a-zA-z][a-zA-Z0-9_]* )*[a-zA-z][a-zA-Z0-9_]*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tiposValidos">
		<xs:restriction base="xs:string">
			<xs:pattern value="INT|ENUM|CHAR|VARCHAR|DATE|DATETIME|DECIMAL" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoListaValores">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-zA-Zá-úÁ-Ú0-9_]+ )*[a-zA-Zá-úÁ-Ú0-9_]+" />
			<xs:whiteSpace value="replace"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== pmcastell/prj.old/prj/php/tema3-4-xml-java/bin/estructuraBdSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<estructuraBD nombre="videoclub2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="estructuraBd.xsd">
    <tablas nombre="peliculas">
        <campo nombre="cod" tipo="INT" longitud="5" />        
        <campo nombre="titulo" tipo="VARCHAR" longitud="40" />
        <campo nombre="genero" tipo="ENUM" lista_de_valores="Humor AcciÃ³n Thriller" null="1" />
        <primary_key campos_clave="cod" />
    </tablas>
    <tabla nombre="clientes">
        <campo nombre="cod" tipo="INT" longitud="4" />
        <campo nombre="nombre" tipo="VARCHAR" longitud="20" />
        <campo nombre="ap1" tipo="VARCHAR" longitud="20" />
        <campo nombre="ap2" tipo="VARCHAR" longitud="20" null="1" />
        <primary_key campos_clave="cod" />
    </tabla>
    <tabla nombre="alquileres">
        <campo nombre="clientes_cod" tipo="INT" longitud="4" />
        <campo nombre="peliculas_cod" tipo="INT" longitud="5" />
        <campo nombre="fecha" tipo="DATETIME" />
        <campo nombre="precio" tipo="DECIMAL" longitud="5" />
        <primary_key campos_clave="clientes_cod peliculas_cod fecha" />
        <foreign_key campos_clave="clientes_cod"  tabla_ajena="clientes" campos_relacionados="cod" />
        <foreign_key campos_clave="peliculas_cod" tabla_ajena="peliculas" campos_relacionados="cod" />
    </tabla>
    <tabla nombre="ingresos">
        <campo nombre="clientes_cod" tipo="INT" longitud="4"/>
        <campo nombre="fecha" tipo="DATETIME"/>
        <campo nombre="cantidad" tipo="DECIMAL" longitud="5"/>
        <primary_key campos_clave="clientes_cod fecha"/>
        <foreign_key campos_clave="clientes_cod" tabla_ajena="clientes" campos_relacionados="cod"/>
    </tabla>
    <tabla nombre="reservas">
        <campo nombre="clientes_cod" tipo="INT" longitud="4"/>
        <campo nombre="peliculas_cod" tipo="INT" longitud="5"/>
        <campo nombre="fecha" tipo="DATETIME"/>
        <campo nombre="precio" tipo="DECIMAL" longitud="5"/>
        <primary_key campos_clave="clientes_cod"/>
        <foreign_key campos_clave="clientes_cod" tabla_ajena="clientes" campos_relacionados="cod"/>
        <foreign_key campos_clave="peliculas_cod" tabla_ajena="peliculas" campos_relacionados="cod"/>
    </tabla>
</estructuraBD>
