=== pmcastell/prj.old/php/videoclubXsl/videoclub.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:element name="videoclub">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="pelicula" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="titulo" type="xs:string" />
							<xs:element name="nacionalidad" type="xs:string" />
							<xs:element name="productor" type="xs:string" />
							<xs:element name="director" type="xs:string" />
							<xs:element name="año" type="tipoAño" />
							<xs:element name="duracion" type="tipoDuracion" />
							<xs:element name="genero" type="tipoGenero" minOccurs="1"
								maxOccurs="unbounded" />
							<xs:element name="sinopsis" type="xs:string" />
							<xs:element name="foto" type="tipoFoto" />
							<xs:element name="url" type="tipoUrl" />
						</xs:sequence>
						<xs:attribute name="id" type="xs:ID" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="tipoAño">
		<xs:restriction base="xs:integer">
			<xs:pattern value="(18[789][0-9]|19[0-9][0-9]|200[0-9]|201[012])" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoDuracion">
		<xs:restriction base="xs:integer">
			<xs:pattern value="[0-9]{1,3}" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoGenero">
		<xs:restriction base="xs:string">
			<xs:pattern value="Drama|Romance|Crimen|Thriller|Comedia" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoFoto">
		<xs:restriction base="xs:string">
			<xs:pattern value=".*\.(jpg|png|gif)" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoUrl">
		<xs:restriction base="xs:string">
			<xs:pattern value="http://www.imdb.com/.*" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== pmcastell/prj.old/prj/php/videoclubXsl/videoclub.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="pelisXml.xsl"?>
<videoclub xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="videoclub.xsd"> 
    <pelicula id="_1">
        <titulo>Las Normas de la Casa de la Sidra</titulo>
        <nacionalidad>EEUU</nacionalidad>
        <productor>Alan C. Blomquist</productor>
        <director>Lasse Hallström</director>
        <año>1999</año> 
        <duracion>126</duracion> 
        <genero>Drama</genero> 
        <genero>Romance</genero> 
        <sinopsis>
            A compassionate young man, raised in an orphanage and trained to be a doctor there, 
            decides to leave to see the world.
        </sinopsis>
        <foto>lasNormasDeLaCasaDeLaSidra.jpg</foto> 
        <url>http://www.imdb.com/title/tt0124315/</url> 
    </pelicula>
    <pelicula id="_2">
        <titulo>Los idus de marzo</titulo>
        <nacionalidad>EEUU</nacionalidad>
        <productor>George Clooney</productor>
        <director>George Clooney</director>
        <año>2011</año>
        <duracion>101</duracion>
        <genero>Drama</genero>
        <sinopsis>
            An idealistic staffer for a new presidential candidate gets a crash course on dirty 
            politics during his stint on the campaign trail.
        </sinopsis>
        <foto>losIdusDeMarzo.jpg</foto>
        <url>http://www.imdb.com/title/tt1124035/</url>
    </pelicula>
    <pelicula id="_3">
        <titulo>Cadena Perpetua</titulo>
        <nacionalidad>EEUU</nacionalidad>
        <productor>Liz Glotzer</productor>
        <director>Frank Darabont</director>
        <año>1994</año>
        <duracion>142</duracion>
        <genero>Crimen</genero>
        <genero>Drama</genero>
        <sinopsis>
            Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency. 
        </sinopsis>
        <foto>cadenaPerpetua.jpg</foto>
        <url>http://www.imdb.com/title/tt0111161/</url>
    </pelicula>
    <pelicula id="_4">
        <titulo>Thelma y Louise</titulo>
        <nacionalidad>EEUU</nacionalidad>
        <productor>Mimi Polk Gitlin</productor>
        <director>Ridley Scott</director>
        <año>1991</año>
        <duracion>130</duracion>
        <genero>Crimen</genero>
        <genero>Drama</genero>
        <sinopsis>
            An Arkansas waitress and a housewife shoot a rapist and take off in a '66 Thunderbird. 
        </sinopsis>
        <foto>thelmaYlouise.jpg</foto>
        <url>http://www.imdb.com/title/tt0103074/</url>
    </pelicula>
    <pelicula id="_5">
        <titulo>Pulp Fiction</titulo>
        <nacionalidad>EEUU</nacionalidad>
        <productor>Lawrence Bender</productor>
        <director>Quentin Tarantino</director>
        <año>1994</año>
        <duracion>154</duracion>
        <genero>Crimen</genero>
        <genero>Thriller</genero>
        <sinopsis>
            The lives of two mob hit men, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption. 
        </sinopsis>
        <foto>pulpFiction.jpg</foto>
        <url>http://www.imdb.com/title/tt0110912/</url>
    </pelicula>
    <pelicula id="_6">
        <titulo>Hable con ella</titulo>
        <nacionalidad>ES</nacionalidad>
        <productor>Agustín Almodóvar    </productor>
        <director>Pedro Almodóvar</director>
        <año>2002</año>
        <duracion>112</duracion>
        <genero>Comedia</genero>
        <genero>Drama</genero>
        <sinopsis>
             Two men share an odd friendship while they care for their girlfriends who are both in deep comas. 
        </sinopsis>
        <foto>hableConElla.jpg</foto>
        <url>http://www.imdb.com/title/tt0287467/</url>
    </pelicula>
    <pelicula id="_7">
        <titulo>Solas</titulo>
        <nacionalidad>ES</nacionalidad>
        <productor>Antonio P. Pérez</productor>
        <director>Benito Zambrano</director>
        <año>1999</año>
        <duracion>101</duracion>
        <genero>Drama</genero>
        <sinopsis>
             Maria, whose parents live in the country, cannot stand her father's authoritarian ways and moves to the city...
        </sinopsis>
        <foto>solas.jpg</foto>
        <url>http://www.imdb.com/title/tt0190798/</url>
    </pelicula>
    <pelicula id="_8">
        <titulo>El Amor Perjudica Seriamente La Salud</titulo>
        <nacionalidad>ES</nacionalidad>
        <productor>César Benítez</productor>
        <director>Manuel Gómez Pereira</director>
        <año>1996</año>
        <duracion>117</duracion>
        <genero>Comedia</genero>
        <genero>Romance</genero>
        <sinopsis>
             Two young people meet in the 60's as a result of their devotion to John Lennon, and have a recurring relationship during 
             the next thirty years at the oddest of moments...
        </sinopsis>
        <foto>elAmorPerjudicaSeriamenteLaSalud.jpg</foto>
        <url>http://www.imdb.com/title/tt0115536/</url>
    </pelicula>
    <pelicula id="_9">
        <titulo>La Buena Estrella</titulo>
        <nacionalidad>ES</nacionalidad>
        <productor>Enrique Cerezo</productor>
        <director>Ricardo Franco</director>
        <año>1997</año>
        <duracion>95</duracion>
        <genero>Drama</genero>
        <sinopsis>
             Marina, a woman with a glass eye, has the bad luck to be the victim of an assault witnessed by Rafael...
        </sinopsis>
        <foto>laBuenaEstrella.jpg</foto>
        <url>http://www.imdb.com/title/tt0118788/</url>
    </pelicula>
    <pelicula id="_10">
        <titulo>Atraco A Las Tres</titulo>
        <nacionalidad>ES</nacionalidad>
        <productor>José Alted</productor>
        <director>José María Forqué</director>
        <año>1962</año>
        <duracion>92</duracion>
        <genero>Comedia</genero>
        <sinopsis>
            Galindo works in a bank. One day he convinces the other employees in the bank to plan a hold-up in the bank they are working... 
        </sinopsis>
        <foto>atracoAlasTres.jpg</foto>
        <url>http://www.imdb.com/title/tt0055763/</url>
    </pelicula>
</videoclub>
